---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openshift.kemo.dev
  resources:
  - upgradeaccelerators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openshift.kemo.dev
  resources:
  - upgradeaccelerators/finalizers
  verbs:
  - update
- apiGroups:
  - openshift.kemo.dev
  resources:
  - upgradeaccelerators/status
  verbs:
  - get
  - patch
  - update
