name: Operator - Build Operator Container

# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write

env:
  REGISTRY_HOSTNAME: quay.io
  REGISTRY_IMAGE: quay.io/kenmoini/openshift-upgrade-accelerator-operator
  CONTAINERFILE_PATH: Dockerfile
  #BUILD_CONTEXT_PATH: .

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - DEV.md
      - RELEASE.md
      - .github/dependabot.yml
      - .github/workflows/**
      - .devcontainer/**

  # Schedule workflow run at 02:00 on Sunday
  schedule:
    - cron: '0 2 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-and-tap:
    name: Run tests and submit dependencies for TAP
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.0

      - name: Run snapshot action to submit dependencies
        uses: actions/go-dependency-submission@v2
        with:
          # Required: Define the repo path to the go.mod file used by the
          # build target
          go-mod-path: go.mod
          #
          # Optional: Define the path of a build target (a file with a
          # `main()` function) If not defined, this Action will collect all
          # dependencies used by all build targets for the module, which may
          # include Go dependencies used by tests and tooling.
          go-build-target: cmd/main.go

      - name: Running Tests
        run: |
          go mod tidy
          make test

  # Build the container
  # Check if we can build multi-arch faster
  # https://learn.arm.com/learning-paths/cross-platform/github-arm-runners/actions/
  # https://skyworkz.nl/blog/multi-arch-docker-image-10x-faster
  build:
    name: Build Container
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs:
      - test-and-tap
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          # Release images are multi-arch - this workflow just builds main for integration
          # Multi-arch works, work through quick bugs first before initial release
          #- linux/arm64
          #- linux/ppc64le
          #- linux/s390x
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Login to Quay Container Registry
        uses: docker/login-action@v3
        with:
          registry: "${{ env.REGISTRY_HOSTNAME }}"
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_TOKEN }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out code
        uses: actions/checkout@v5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.REGISTRY_IMAGE }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          tags: ${{ env.REGISTRY_IMAGE }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          context: ${{ env.BUILD_CONTEXT_PATH }}
          file: ${{ env.CONTAINERFILE_PATH }}
          labels: ${{ steps.meta.outputs.labels }}
          #push: true
          #provenance: false
          #platforms: linux/amd64, linux/arm64
          #provenance: mode=max
          #sbom: true
          #cache-from: type=gha
          #cache-to: type=gha,mode=max

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: Create and Push Manifest List
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v5
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: "${{ env.REGISTRY_HOSTNAME }}"
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_TOKEN }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=,suffix=,format=short
            type=sha,prefix=,suffix=,format=long
            type=raw,value=latest

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}

      - name: Generate SBOM for container image
        uses: anchore/sbom-action@v0.20.6
        with:
          image: ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
          dependency-snapshot: true
      #- name: Container Dependency Submission Action
      #  uses: GeekMasher/container-dependency-submission-action@main
      #  with:
      #    # `container` is the name of the container already built on the system
      #    container: ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
      #    token: ${{ secrets.GITHUB_TOKEN }}