# Always run basic Golang linting
name: Lint

on:
  push:
    paths-ignore:
      - README.md
      - DEV.md
      - RELEASE.md
      - .github/dependabot.yml
      - .github/workflows/**
      - .devcontainer/**
  pull_request:
    paths-ignore:
      - README.md
      - DEV.md
      - RELEASE.md
      - .github/dependabot.yml
      - .github/workflows/**
      - .devcontainer/**

jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.0
