name: Tests

on:
  push:
    paths-ignore:
      - README.md
      - DEV.md
      - RELEASE.md
      - .github/dependabot.yml
      - .github/workflows/**
      - .devcontainer/**
  pull_request:
    paths-ignore:
      - README.md
      - DEV.md
      - RELEASE.md
      - .github/dependabot.yml
      - .github/workflows/**
      - .devcontainer/**

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.24.0"
          go-version-file: go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test
